# Streaming frame ambient light test
/rat/db/set DETECTOR experiment "Validation"
/rat/db/set DETECTOR geo_file "Validation/Valid.geo"


# Dummy generator (0 photons) to satisfy Geant4
/generator/add combo pbomb:point:poisson
/generator/pos/set 0.0 0.0 0.0
/generator/vtx/set 0 400
/generator/rate/set 1.0

/rat/proc streamingdaq
/rat/proc streamingframe
/rat/procset frame_window_length_ms 100.0

/rat/proc ambientlight
/rat/procset rate 70.0

/rat/proc outntuple
/rat/procset file "output_ambient_light.root"
/rat/procset include_frame_info 1
/rat/procset include_frame_ambient 1

/run/initialize
/run/beamOn 1000
