# Generate frames without G4 primaries
/rat/db/set DETECTOR experiment "Validation"
/rat/db/set DETECTOR geo_file "Validation/Valid.geo"
/rat/db/set IO[NtupleProc] include_frame_info true

/rat/proc streamingdaq
/rat/proc streamingframe
/rat/procset frame_window_length_ms 100.0

/rat/proc outntuple
/rat/procset file "output_frame_meta.root"

/generator/add combo pbomb:point:poisson
/generator/pos/set 0.0 0.0 0.0
/generator/vtx/set 0 400      # 0 photons, 400nm wavelength
/generator/rate/set 1.0       # Poisson rate to keep time generator valid

/run/initialize
/run/beamOn 1000
